version: '{build}'
image: Visual Studio 2017

build:
  verbosity: minimal

branches:
  only: 
    - master

skip_tags: true

build_script:
- ps: .\build.ps1

test: off

artifacts:
- path: .artifacts/**/output
