version: '{build}'
skip_tags: true
image: Visual Studio 2017

build:
  verbosity: minimal

branches:
  only: 
    - master

build_script:
  - ps: ./build.ps1

test: off

artifacts:
  - path: .artifacts/**/output
