version: '{build}'
skip_tags: true
image: Ubuntu 18.04 LTS

build:
  verbosity: minimal

branches:
  only: 
    - master

build_script:
  - ps: ./build.ps1

test: off

artifacts:
  - path: .artifacts/**/output
